name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Find changed folders
      id: changed_folders
      run: |
        changed_folders=$(git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.event.after }} | xargs -I{} dirname {})
        echo "Changed folders: $changed_folders"
        echo "::set-output name=folders::$changed_folders"

    - name: Build and push Docker images
      run: |
        for folder in ${{ steps.changed_folders.outputs.folders }}
        do
          if [ "$folder" == "client" ]; then
              my_ecr_repo="spiral-client-miki"
          elif [ "$folder" == "server" ]; then
              my_ecr_repo="spiral-server-miki"
          elif [ "$folder" == "worker" ]; then
              my_ecr_repo="spiral-worker-miki"
          else
              echo "Invalid input. changes are accorded only on 'client', 'server', or 'worker'."
          fi
          ecr_repository="${{ steps.login-ecr.outputs.registry }}/$my_ecr_repo"
          # Get the current image tag
          current_tag=$(aws ecr describe-images --repository-name $my_ecr_repo --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)

          # Increment the tag by 0.1
          new_tag=$(echo "$current_tag + 0.1" | bc)

          docker build -t $ecr_repository:$new_tag $folder
          docker push $ecr_repository:$new_tag
        done