name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    environment:
        name: Deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Find changed folders
      id: changed_folders
      run: |
        target_folders=("worker" "client" "server")
        changed_folders=()
        for folder in "${target_folders[@]}"; do
          if git diff HEAD^ HEAD --name-only | grep -q "^$folder/"; then
            changed_folders+=("$folder")
          fi
        done
        changed_folders_string="${changed_folders[*]}"
        echo "::set-output name=folders::$changed_folders_string"

    - name: Build and push changed folders
      run: |
        changed_folders=${{ steps.changed_folders.outputs.folders }}

        IFS=' ' read -ra changed_folders_array <<< "$changed_folders"
        for folder in "${changed_folders_array[@]}"; do
          if [ "$folder" == "client" ]; then
              my_ecr_repo="spiral-client-miki"
          elif [ "$folder" == "server" ]; then
              my_ecr_repo="spiral-server-miki"
          elif [ "$folder" == "worker" ]; then
              my_ecr_repo="spiral-worker-miki"
          else
              echo "$folder"
          fi

          ecr_repository="${{ steps.login-ecr.outputs.registry }}/$my_ecr_repo"
          current_tag=$(aws ecr describe-images --repository-name $my_ecr_repo --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
          new_tag=$(echo "$current_tag + 0.1" | bc)
          value_file="./helm/values.$folder.yaml"
          yq eval -i ".$folder.tag = \"$new_tag\"" "$value_file"
          cat $value_file
          docker build -t $ecr_repository:$new_tag $folder
          docker push $ecr_repository:$new_tag
        done
    
    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit and push Helm chart changes
      if: ${{ steps.changed_folders.outputs.folders != '' }}
      run: |
        git add -A
        git commit -m "Update Helm chart tag"
        git push
      